quotes = [
  "Doing nothing is very hard to do… you never know when you're finished — Leslie Nielsen",
  "If you think your boss is stupid, remember: you wouldn't have a job if he was any smarter. — John Gotti",
  "I like work; it fascinates me. I can sit and look at it for hours. — Jerome K. Jerome",
  "The brain is a wonderful organ; it starts working the moment you get up in the morning and does not stop until you get into the office. — Robert Frost",
  "People say nothing is impossible, but I do nothing every day! — Anonymous",
  "I think Smithers picked me because of my motivational skills. Everyone says they have to work a lot harder when I'm around. — Homer Simpson",
  "I love deadlines. I like the whooshing sound they make as they fly by",
  "Roses are red, violets are blue. I'm schizophrenic, and so am I",
  "There cannot be a crisis next week.  My schedule is already full",
  "I haven't spoken to my wife in years.  I didn't want to interupt her- Rodney Dangerfield",
  "Progress is humans ability to complicate simplicity",
  "One advantage of talking to yourself is that you know at least somebodys listening - Franklin Jones",
  "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it - Terry Pratchet",
  "Procrastination is the art of keeping up with yesterday - Don Marquies",
  "I used to jog, but the ice cubes kept falling out of my glass - David Lee Roth",
  "If you haven't got anything nice to say about anybody, come sit next to me - Alice Longworth",
  "STRESS: The confusion caused when one's mind overides the body's basic need to choke the living crap out of some idiot who desperately needs it",
  "Of course I talk to myself.  Sometimes I need expert advice",
  "I'd agree with you, but then we'd both be wrong",
  "I'm not lazy.  I'm just very relaxed",
  "The problem is, I'm speaking English and you're listening in dumbass",
  "We don't choose to do something that's hard, we chose to do it because we thought it would be easy",
  "All you need in this life is ignorance and confidence, and then success is sure - Mark Twain",
  "If you don't know where you're going, you might wind up someplace else - Yogi Berra",
  "Don't worry about the world coming to an end today.  It is already tomorrow in Australia - Charles Schulz",
  "I didn't fail the test.  I just found 100 ways to do it wrong - Benjamin Franklin",
  "Kiwi scientists have made a breakthrough discovery and discovered 2 new uses for sheep - Meat and Wool",
  "If at first you don't succeed - try management",
  "Two things are infinite: the universe and human stupidity; and i'm not sure about the universe",
  "Sometimes when I close my eyes, I can't see",
  "Stupidity isn't punishable by death.  If it was, there would be a hell of a population drop",
  "My back up plan is my original plan but with more alcohol",
  "Patience: What you have when there are too many witnesses",
  "I don't understand your specific kind of crazy but I do admire your total commitment to it.",
  "I feel the need, the need for expeditious velocity - The Pinky & the Brain",
  "There is no try, only do and royally f**king up, and you are royally f**king - Robot Chicken"
]