# Generated by Django 4.1.5 on 2023-01-28 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_project_concated_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_assigned_to',
            field=models.ForeignKey(blank=True, default='Nobody', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.technician'),
        ),
    ]
