# Generated by Django 4.1.5 on 2023-01-28 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_task_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.technician'),
        ),
    ]
