# Generated by Django 4.1.5 on 2023-01-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_task_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_concated_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_modified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
