# Generated by Django 4.1.5 on 2023-01-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_task_task_concated_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
