# Generated by Django 4.1.5 on 2023-02-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_project_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectowners',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
    ]
