# Generated by Django 4.1.5 on 2023-03-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projectowners_status_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_shift',
            field=models.CharField(choices=[('FD', 'FD'), ('AM', 'AM'), ('PM', 'PM'), ('NS', 'NS')], default='FD', max_length=25),
        ),
    ]
