# Generated by Django 4.1.5 on 2023-03-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_task_task_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_pan',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
