# Generated by Django 4.1.5 on 2023-03-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_task_task_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(max_length=5000),
        ),
    ]
