# Generated by Django 4.1.5 on 2023-03-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_task_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulverise', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Other', 'Other')], default='Yes', max_length=10)),
                ('assay_method', models.CharField(max_length=200)),
            ],
        ),
    ]
