# Generated by Django 4.1.5 on 2023-03-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_assaydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_by', models.CharField(max_length=50)),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
                ('edit_reason', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.task')),
            ],
            options={
                'ordering': ['-edit_date'],
            },
        ),
    ]
