# Generated by Django 4.1.5 on 2023-03-22 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_task_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_reason', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='taskedit',
            name='edit_reason',
            field=models.ForeignKey(default='Nil', on_delete=django.db.models.deletion.CASCADE, to='project.editreason'),
        ),
    ]
