# Generated by Django 4.1.5 on 2023-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_editreason_alter_taskedit_edit_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_due_date',
            new_name='task_request_date',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_priority',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=20),
        ),
    ]
