# Generated by Django 4.1.5 on 2023-03-29 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_delete_assaydetails_remove_task_task_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskedit',
            name='edit_reason',
            field=models.ForeignKey(default='Nil', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.editreason'),
        ),
    ]
